const state={mode:"live",fixtures:[],markets:new Map(),selectedId:null,selectedOutcome:null,balance:1000,positions:[],replayIndex:0,replayTimer:null,scannedAt:null,busy:false};
const $=s=>document.querySelector(s);const stageOrder=["OPEN","LOCKED","RESOLVED","SETTLED"];

function normalizeOdds(fixture,rows=[]){const row=rows.find(r=>r.SuperOddsType==="1X2_PARTICIPANT_RESULT"&&r.MarketPeriod==="half=0")||rows.find(r=>r.SuperOddsType==="1X2_PARTICIPANT_RESULT")||rows[0];if(!row||!Array.isArray(row.PriceNames))return equalOutcomes(fixture);const raw=(row.Pct||row.Prices?.map(p=>100/(Number(p)/1000)))?.map(Number);if(!raw||raw.some(v=>!Number.isFinite(v)||v<0))return equalOutcomes(fixture);const total=raw.reduce((a,b)=>a+b,0)||1;return row.PriceNames.map((name,i)=>({name:name==="part1"?fixture.Participant1:name==="part2"?fixture.Participant2:name==="draw"?"Draw":name,pct:raw[i]/total*100}))}
function equalOutcomes(f){return[{name:f.Participant1,pct:40},{name:"Draw",pct:30},{name:f.Participant2,pct:30}]}
function normalizeScore(rows=[]){if(!Array.isArray(rows)||!rows.length)return{score:[null,null],label:"No score observation",final:false,ts:null};const row=rows[rows.length-1];const nums=[row.Participant1Score,row.Participant2Score,row.Score1,row.Score2,row.HomeScore,row.AwayScore].map(Number);let score=Number.isFinite(nums[0])&&Number.isFinite(nums[1])?[nums[0],nums[1]]:Number.isFinite(nums[2])&&Number.isFinite(nums[3])?[nums[2],nums[3]]:Number.isFinite(nums[4])&&Number.isFinite(nums[5])?[nums[4],nums[5]]:[null,null];const phase=String(row.GameState||row.State||row.Status||"").toLowerCase();return{score,label:row.Comment||row.ActionComment||row.GameState||"Source observation",final:/final|finished|ended|full.?time/.test(phase),ts:Number(row.Ts||row.Timestamp)||null}}
function marketFromLive(fixture,payload){const score=normalizeScore(payload?.scores);return{fixture,outcomes:normalizeOdds(fixture,payload?.odds),score:score.score,label:score.label,final:score.final,ts:score.ts||state.scannedAt,state:score.final?"RESOLVED":"OPEN",source:"TxLINE live",receipt:null}}

async function loadLive(){if(state.busy)return;state.busy=true;$("#refresh").disabled=true;try{const response=await fetch("/api/markets",{cache:"no-store"});if(!response.ok)throw new Error(`Feed unavailable (${response.status})`);const data=await response.json();if(state.mode!=="live")return;state.scannedAt=data.scannedAt;state.fixtures=data.fixtures||[];state.markets.clear();state.fixtures.forEach(f=>state.markets.set(f.FixtureId,marketFromLive(f,(data.markets||[]).find(m=>m.fixtureId===f.FixtureId))));if(!state.markets.has(state.selectedId))state.selectedId=state.fixtures[0]?.FixtureId||null;$("#source-status").textContent="TXLINE LIVE · SOURCE CONNECTED";render()}catch(error){if(state.mode==="live"){toast(error.message+" · opening replay lab");setMode("replay")}}finally{state.busy=false;$("#refresh").disabled=false}}
function loadReplay(){const fixture=window.RESOLVE_REPLAY.fixture;const frame=window.RESOLVE_REPLAY.frames[state.replayIndex];state.fixtures=[fixture];state.selectedId=fixture.FixtureId;state.scannedAt=frame.ts;const market={fixture,...frame,source:"Deterministic replay",receipt:null};if(frame.final){market.winner=frame.score[0]===frame.score[1]?"Draw":frame.score[0]>frame.score[1]?fixture.Participant1:fixture.Participant2}if(frame.state==="SETTLED")market.receipt=buildReceipt(market);state.markets=new Map([[fixture.FixtureId,market]]);settleEligible(market);$("#source-status").textContent="REPLAY LAB · FRAME VERIFIED";render()}
function setMode(mode){state.mode=mode;clearInterval(state.replayTimer);state.replayTimer=null;state.selectedOutcome=null;document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("#replay-controls").hidden=mode!=="replay";if(mode==="replay"){state.replayIndex=0;loadReplay()}else loadLive()}
function advanceReplay(){state.replayIndex=Math.min(state.replayIndex+1,window.RESOLVE_REPLAY.frames.length-1);loadReplay();if(state.replayIndex===window.RESOLVE_REPLAY.frames.length-1){$("#autoplay").checked=false;clearInterval(state.replayTimer);state.replayTimer=null}}
function toggleAutoplay(){clearInterval(state.replayTimer);state.replayTimer=null;if($("#autoplay").checked)state.replayTimer=setInterval(advanceReplay,4000)}

function selectOutcome(name){const market=state.markets.get(state.selectedId);if(!market||market.state!=="OPEN")return;state.selectedOutcome=name;renderSlip(market);renderOutcomes(market)}
function placePosition(){const market=state.markets.get(state.selectedId);const stake=Number($("#stake").value);if(!market||market.state!=="OPEN"||!state.selectedOutcome||!Number.isFinite(stake)||stake<10||stake>state.balance)return toast("Check outcome, stake and demo balance");const outcome=market.outcomes.find(o=>o.name===state.selectedOutcome);const position={id:`P-${Date.now().toString(36).toUpperCase()}`,createdAt:Date.now(),fixtureId:market.fixture.FixtureId,matchup:`${market.fixture.Participant1} v ${market.fixture.Participant2}`,outcome:outcome.name,probability:outcome.pct,stake,payout:0,status:"OPEN",receipt:null};state.positions.unshift(position);state.balance-=stake;persist();toast("Demo position accepted");render()}
function settleEligible(market){if(market.state!=="SETTLED"||!market.final||!market.winner)return;state.positions.filter(p=>p.fixtureId===market.fixture.FixtureId&&p.status==="OPEN").forEach(p=>{p.status="SETTLED";p.receipt=market.receipt?.hash||buildReceipt(market).hash;if(p.outcome===market.winner){p.payout=Math.round(p.stake*(100/p.probability)*100)/100;state.balance+=p.payout}});persist()}
function fnv1a(text){let hash=0x811c9dc5;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,0x01000193)}return(hash>>>0).toString(16).padStart(8,"0")}
function buildReceipt(market){const fixtureId=market.fixture.FixtureId;const winner=market.winner||(market.score[0]===market.score[1]?"Draw":market.score[0]>market.score[1]?market.fixture.Participant1:market.fixture.Participant2);const canonical=`${fixtureId}|${market.ts}|${market.score.join(":")}|${winner}`;return{version:"resolvekit-v1",fixtureId,sourceTimestamp:market.ts,score:market.score.join(":"),winner,rule:"FULL_TIME_PARTICIPANT_RESULT",hash:`rk_${fnv1a(canonical)}`}}
function persist(){localStorage.setItem("resolvekit-state-v2",JSON.stringify({balance:state.balance,positions:state.positions}))}
function restore(){try{const saved=JSON.parse(localStorage.getItem("resolvekit-state-v2"));if(saved){state.balance=Number(saved.balance)||1000;state.positions=Array.isArray(saved.positions)?saved.positions:[]}}catch{}}

function render(){const market=state.markets.get(state.selectedId);$("#market-count").textContent=state.markets.size;$("#fixture-count").textContent=state.fixtures.length;$("#settlement-count").textContent=state.positions.filter(p=>p.status==="SETTLED").length;$("#balance").textContent=`${state.balance.toLocaleString(undefined,{maximumFractionDigits:2})} CR`;$("#source-age").textContent=state.scannedAt?`${Math.max(0,Math.round((Date.now()-state.scannedAt)/1000))}s`:`--`;renderFixtures();if(!market)return;$("#selected-fixture").textContent=market.fixture.FixtureId;$("#competition").textContent=market.fixture.Competition||"TXLINE FIXTURE";$("#matchup").textContent=`${market.fixture.Participant1} vs ${market.fixture.Participant2}`;$("#market-meta").textContent=`${market.source} · Winner market · Demo credits`;$("#market-state").textContent=market.state;$("#market-state").className=`state-badge ${market.state.toLowerCase()}`;renderLifecycle(market.state);renderOutcomes(market);renderEvidence(market);renderReceipt(market);renderSlip(market);renderLedger();if(state.mode==="replay")$("#frame-label").textContent=`${state.replayIndex+1} / ${window.RESOLVE_REPLAY.frames.length}`}
function renderFixtures(){$("#fixture-list").innerHTML=state.fixtures.map(f=>{const m=state.markets.get(f.FixtureId);return`<button class="fixture-item ${f.FixtureId===state.selectedId?"active":""}" data-fixture="${f.FixtureId}"><strong>${escapeHtml(f.Participant1)}<br>${escapeHtml(f.Participant2)}</strong><div><span>#${f.FixtureId}</span><span>${m?.state||"OPEN"}</span></div></button>`}).join("")||`<div class="selection-empty">No fixtures available</div>`;document.querySelectorAll("[data-fixture]").forEach(b=>b.onclick=()=>{state.selectedId=Number(b.dataset.fixture);state.selectedOutcome=null;render()})}
function renderLifecycle(stage){const index=stageOrder.indexOf(stage);document.querySelectorAll(".lifecycle li").forEach((li,i)=>{li.className=i<index?"done":i===index?"active":""})}
function renderOutcomes(market){$("#outcomes").innerHTML=market.outcomes.map(o=>`<button class="outcome ${state.selectedOutcome===o.name?"selected":""}" data-outcome="${escapeHtml(o.name)}" ${market.state!=="OPEN"?"disabled":""}><span>${escapeHtml(o.name)}</span><strong>${o.pct.toFixed(1)}%</strong></button>`).join("");document.querySelectorAll("[data-outcome]").forEach(b=>b.onclick=()=>selectOutcome(b.dataset.outcome))}
function renderEvidence(m){$("#score").textContent=m.score?.every(Number.isFinite)?m.score.join(" : "):"-- : --";$("#clock").textContent=m.label||"Awaiting observation";$("#evidence-fixture").textContent=m.fixture.FixtureId;$("#evidence-ts").textContent=m.ts?new Date(m.ts).toISOString():"--";$("#integrity").textContent=m.final?"Final result observed":m.source.includes("replay")?"Replay source-bound":"TxLINE source-bound"}
function renderReceipt(m){const receipt=m.receipt||(m.state==="SETTLED"?buildReceipt(m):null);$("#receipt").textContent=receipt?JSON.stringify(receipt,null,2):"No settlement receipt yet. A receipt is generated only after a final score is observed.";$("#copy-receipt").disabled=!receipt;$("#copy-receipt").onclick=()=>receipt&&navigator.clipboard.writeText(JSON.stringify(receipt,null,2)).then(()=>toast("Receipt copied"))}
function renderSlip(m){const selected=m.outcomes.find(o=>o.name===state.selectedOutcome);$("#selected-outcome").className=selected?"selection":"selection-empty";$("#selected-outcome").innerHTML=selected?`<strong>${escapeHtml(selected.name)}</strong><span>${selected.pct.toFixed(1)}% implied probability · demo quote</span>`:"Select an outcome";const stake=Number($("#stake").value)||0;$("#potential-return").textContent=selected?`${(stake*(100/selected.pct)).toFixed(2)} CR`:"--";$("#place-position").disabled=!selected||m.state!=="OPEN"||stake<10||stake>state.balance}
function renderLedger(){$("#ledger-body").innerHTML=state.positions.length?state.positions.map(p=>`<tr><td>${new Date(p.createdAt).toLocaleTimeString()}</td><td>${escapeHtml(p.matchup)}</td><td>${escapeHtml(p.outcome)}</td><td>${p.stake.toFixed(2)} CR</td><td><span class="status-chip ${p.status.toLowerCase()}">${p.status}</span></td><td>${p.payout?p.payout.toFixed(2)+" CR":"--"}</td><td>${p.receipt||"Pending"}</td></tr>`).join(""):`<tr><td colspan="7" class="empty-row">No demo positions yet</td></tr>`}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(message){$("#toast").textContent=message;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2400)}

document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll("[data-stake]").forEach(b=>b.onclick=()=>{$("#stake").value=b.dataset.stake;renderSlip(state.markets.get(state.selectedId))});$("#stake").oninput=()=>state.markets.has(state.selectedId)&&renderSlip(state.markets.get(state.selectedId));$("#place-position").onclick=placePosition;$("#refresh").onclick=()=>state.mode==="live"?loadLive():loadReplay();$("#advance-frame").onclick=advanceReplay;$("#autoplay").onchange=toggleAutoplay;restore();loadLive();setInterval(()=>{if(state.scannedAt)$("#source-age").textContent=`${Math.max(0,Math.round((Date.now()-state.scannedAt)/1000))}s`},1000);
